name: Check File Modification on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  check-file-modification:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
        
      - name: Check if common/abc.py was modified
        id: check-file
        run: |
          if git diff --name-only ${{ github.event.before }}...${{ github.event.after }} | grep -q "^common/abc.py$"; then
            echo "common/abc.py was modified."
            echo "::set-output name=file_modified::true"
          else
            echo "common/abc.py was not modified."
            echo "::set-output name=file_modified::false"
          fi

      - name: Display result
        run: |
          if [ "${{ steps.check-file.outputs.file_modified }}" == "true" ]; then
            echo "The file common/abc.py was modified."
          else
            echo "The file common/abc.py was not modified."
          fi
