name: Test Restriction

on:
    push:
        branches:
            - main
    pull_request:
        types:
            - opened
            - synchronize

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Get actor name
              run: echo "Actor name ${{ github.actor }}"

            - name: Check for changes in common/dag.py
              id: check_changes
              run: |
                if git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -q '^common/dag.py$'; then
                  echo "common/dag.py was modified in this pull request."
                  echo "::set-output name=changed::true"
                else
                  echo "common/dag.py was NOT modified in this pull request."
                  echo "::set-output name=changed::false"
                fi

            - name: Use the output
              run: |
                if [[ "${{ steps.check_changes.outputs.changed }}" == "true" ]]; then
                  # Perform actions if common/dag.py was modified
                  echo "Performing actions because common/dag.py was modified."
                else
                  echo "No further actions needed."
                fi