name: Test Restriction

on:
    push:
        branches:
            - main
    pull_request:
        types:
            - opened
            - synchronize

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Get actor name
              run: echo "Actor name ${{ github.actor }}"

            - name: Get modified files
              id: modified_files
              run: |
                  git diff --name-only ${{ env.GITHUB_BASE_REF }}...${{ env.GITHUB_HEAD_REF }} | grep "common/"

            - name: Check if files are in common folder
              run: |
                  if [ -z "${{ steps.modified_files.outputs.stdout }}" ]; then
                      echo "No modified files in common folder"
                  else
                      echo "Modified files in common folder:"
                      echo "${{ steps.modified_files.outputs.stdout }}"
                  fi