name: Test Restriction

on:
    push:
        branches:
            - main
    pull_request:
        types:
            - opened
            - synchronize

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Get actor name
              run: echo "Actor name ${{ github.actor }}"

            - name: Check for changes in common/abc.py
              id: check_changes
              run: |
                git fetch ${{ github.repository }} ${{ github.head_ref }}
                git diff --name-only ${{ github.repository }} ${{ github.head_ref }}..HEAD > changed_file.txt                

            - name: Use the output
              run: |
                if grep -q "common/abc.py" changed_files.txt; then
                  echo "filechanged"
                else
                  echo "No further actions needed."
                fi