name: Test Restriction

on:
    push:
        branches:
            - main
    pull_request:
        types:
            - opened
            - synchronize

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Get actor name
              run: echo "Actor name ${{ github.actor }}"

            - name: Get modified files
              id: modified_files
              run: |
                  if git diff --name-only ${{ github.base_ref }}..${{ github.sha }} | grep -e 'dags/dag_factory.py' -e 'dags/bi/' -e 'dags/common/'; then
                    echo "::set-output name=changes::true"
                  else
                    echo "::set-output name=changes::false"
                  fi

            - name: Check if files are in common folder
              run: |
                  if [ -z "${{ steps.modified_files.outputs.stdout }}" ]; then
                      echo "No modified files in common folder"
                  else
                      echo "Modified files in common folder:"
                      echo "${{ steps.modified_files.outputs.stdout }}"
                  fi