name: Check File Modification on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  check-file-modification:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ github.event.pull_request.head.repo.default_branch == 'main' && 2 || 0 }}

      - name: Get changed files
        id: changed-files
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            echo "changed_files=$(git diff --name-only HEAD^ HEAD | xargs)" >> $GITHUB_ENV
          else
            echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_ENV
          fi
      
      - name: List changed files
        run: |
          for file in ${{ env.changed_files }}; do
            echo "$file was changed"
          done
