name: Checkout
on: [push]

jobs:
  checkactions:
    runs-on: ubunty-latest
    steps:
      - name: List Files Before
        run: ls -a
      - uses: actions/checkout@v3
      - name: List Files After
        run: ls -a
          
