name: Environment Variables
on: [push]

jobs:
    env-vars-and-context:
        runs-on: ubuntu-latest
        steps:
            - name: long Env var
              run: echo $GITHBI_REF
            - name: log Context
            # before running the workflow
              run: echo '${{github.ref}}'