name: Context and Expressions
on: [push, pull_request, issues, workflow_dispatch]
run-name: "Expression & Contexts by @${{github.actor }}, event: @${{ github.event_name }}"
jobs:
  expression-and-context:
    runs-on: ubuntu-latest
    steps:
      - name: Expressions
        id: expressions
        run: |
          echo ${{ 1 }}
          echo ${{'this is string'}}
          echo ${{ null }}
          echo ${{ true }}
          echo $ {{ 2>1 }}
      - name: Context
        run: |
          echo '${{ toJson(github) }}'
          echo '${{toJson(job) }}'
          echo '${{ toJson(secrets) }}'
          echo '${{ toJson(steps) }}'
          echo '${{toJson(runner) }}'
          

