name: stauts check
on: [push]

jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: step 1
              run: sleep 20
            - name: runs on failure
              if: failure()
              run: echo 'runs only on failure'
            - name: runs on success
              if: success()
              runs: echo 'runs on success'
            - name: Alaywas runs
              if: always()
              run: echo 'always going to run' 

            - name: Runs when cancelled
              if: cancelled()
              run: echo ' on cancelled'

    job-2:
        runs-on: ubuntu-latest
        needs: job-1
        if: failure()
        steps:
            - run: echo 'job2'

